# Generated by Django 3.1.3 on 2020-11-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_is_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.URLField(default='https://source.unsplash.com/random/250x250', max_length=1000),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist_logo',
            field=models.URLField(default='https://source.unsplash.com/random/300x250', max_length=500),
        ),
    ]
