# Generated by Django 3.1.3 on 2020-11-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20201121_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(upload_to='album_cover'),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist_logo',
            field=models.ImageField(upload_to='artist_cover'),
        ),
    ]
